on:
    workflow_call:
      inputs:
        model-name:
          required: true
          type: string
        workflow-branch:
          required: false
          default: main
          type: string

jobs:
  create-and-annotate-sbml:
    name: Create and annotate SBML
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch SBML PBK workflow files
        uses: actions/checkout@v4
        with:
          repository: 'jwkruisselbrink/sbml-pbk-workflow'
          path: 'sbml-pbk-workflow'
          ref: '${{inputs.workflow-branch}}'
  
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r sbml-pbk-workflow/requirements.txt
        shell: bash

      - name: Create log file folder
        id: create-log-file-folder
        run: |
          mkdir log
        shell: bash

      - name: Create SBML
        id: create-sbml
        run: |
          python sbml-pbk-workflow/src/ant2sbml.py model/${{inputs.model-name}}.ant -o model/${{inputs.model-name}}.sbml -f
        shell: bash

      - name: Annotate SBML
        id: annotate-sbml
        run: |
          if [ -f CITATION.cff ]; then
            (python sbml-pbk-workflow/src/annotate_sbml.py model/${{inputs.model-name}}.sbml model/${{inputs.model-name}}.annotations.csv model/${{inputs.model-name}}.sbml -c CITATION.cff -f) | tee log/annotate-terms.log
          else
            (python sbml-pbk-workflow/src/annotate_sbml.py model/${{inputs.model-name}}.sbml model/${{inputs.model-name}}.annotations.csv model/${{inputs.model-name}}.sbml -f) | tee log/annotate-terms.log
          fi
        shell: bash

      - name: Validate SBML
        id: validate-sbml
        run: (python sbml-pbk-workflow/src/validate_sbml.py model/${{inputs.model-name}}.sbml) | tee log/validate-sbml.log
        shell: bash

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: |
            model/${{inputs.model-name}}.sbml
            *log/

      - name: "Push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Rebuild SBML and annotate model
          file_pattern: '*.sbml'
